# Generated by Django 4.1.1 on 2022-10-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookrecord',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest_book_app.recordstatus'),
        ),
    ]
